#https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
matrix:
  include:
    - stage: build
      language: java
      jdk: oraclejdk8
      script:
      - "./gradlew check"
      after_success:
      - "./gradlew jacocoRootReport coveralls"
      cache:
        directories:
        - "$HOME/.m2"
        - "$HOME/.gradle"
    - stage: bintray
      if: branch = master
      language: bash
      script: "./release-ci.sh"
    - stage: docs
      if: branch = master
      language: python
      script:
      - "./release-site.sh"
    - stage: maven central
      if: branch = master
      script: "travis_wait 90 ./release-maven-central.sh"
      language: bash
