dist: xenial
#https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
matrix:
  include:
    - stage: build
      language: java
      jdk: openjdk11
      script:
        - "./gradlew -i check jacocoRootReport"
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      cache:
        directories:
          - "$HOME/.m2"
          - "$HOME/.gradle"
    - stage: bintray
      if: branch = master AND type != "pull_request"
      language: java
      jdk: openjdk11
      script: 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./release-ci.sh; fi'
    - stage: maven central 1
      if: branch = master AND type != "pull_request"
      script: 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then travis_wait 90 ./release-maven-central-1.sh; fi'
    - stage: maven central 2
      if: branch = master AND type != "pull_request"
      script: 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then travis_wait 90 ./release-maven-central-2.sh; fi'
    - stage: maven central 3
      if: branch = master AND type != "pull_request"
      script: 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then travis_wait 90 ./release-maven-central-3.sh; fi'
    - stage: maven central 4
      if: branch = master AND type != "pull_request"
      script: 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then travis_wait 90 ./release-maven-central-4.sh; fi'
    - stage: tag
      if: branch = master AND type != "pull_request"
      script: 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./release-tag.sh; fi'

