site_name: http4k
site_url: https://www.http4k.org/
site_description: The Functional toolkit for Kotlin HTTP applications
site_author: David Denton (@daviddenton), Ivan Sanchez (@s4nchez)
copyright: 'Copyright &copy; 2022 - David Denton (@daviddenton), IvanSanchez (@s4nchez)'
remote_branch: master
repo_url: https://github.com/http4k/http4k/
theme:
  name: 'material'
  custom_dir: ./docs/theme
  static_templates:
      - ./index.html
  palette:
    primary: 'indigo'
    accent: 'blue'
  logo: img/logo_1100x200_white_on_blue_trans.png
google_analytics: ['UA-125143867-1', 'auto']
markdown_extensions:
  - meta
  - codehilite
  - toc:
      permalink: True
      separator: "_"
extra_css:
  - ./css/site.css
extra:
  logo: img/logo_1100x200_white_on_blue_trans.png
edit_uri: edit/master/src/docs/
strict: false
nav:
  - Introduction: documentation/index.md
  - Quickstart: quickstart/index.md
  - About the docs: guide/index.md
  - Concepts:
    - Rationale: guide/concepts/rationale.md
    - HTTP: guide/concepts/http.md
    - Serverless: guide/concepts/serverless.md
    - WebSockets: guide/concepts/websockets.md
    - Server-Sent Events: guide/concepts/server-sent-events.md
  - Tutorials:
    - Your first http4k app: guide/tutorials/your_first_http4k_app/index.md
    - Deploying an http4k app to AWS Lambda: guide/tutorials/serverless_http4k_with_aws_lambda/index.md
    - Going native with Graal on AWS Lambda: guide/tutorials/going_native_with_graal_on_aws_lambda/index.md
    - TDDing http4k: guide/tutorials/tdding_http4k/index.md
  - How-to guides:
    - Overview: guide/howto/index.md
    - "Basic: Server as a function": guide/howto/server_as_a_function/index.md
    - "Basic: Client as a function": guide/howto/client_as_a_function/index.md
    - "Basic: Use a Server backend": guide/howto/use_a_server_backend/index.md
    - "Basic: Different test-types": guide/howto/write_different_test_types/index.md
    - "Basic: Simple routing": guide/howto/simple_routing/index.md
    - "Basic: Nestable routes": guide/howto/nestable_routes/index.md
    - Attach context to a request: guide/howto/attach_context_to_a_request/index.md
    - Configure an OAuth Server: guide/howto/configure_an_oauth_server/index.md
    - Create a custom JSON marshaller: guide/howto/create_a_custom_json_marshaller/index.md
    - Customise a Server backend: guide/howto/customise_a_server_backend/index.md
    - Deploy WebJars: guide/howto/deploy_webjars/index.md
    - Integrate with OpenAPI: guide/howto/integrate_with_openapi/index.md
    - Leverage GraphQL: guide/howto/leverage_graphql/index.md
    - Lookup a User Principal: guide/howto/lookup_a_user_principal/index.md
    - Monitor http4k: guide/howto/monitor_http4k/index.md
    - Record & replay HTTP traffic: guide/howto/record_and_replay_http_traffic/index.md
    - Serve Server-Sent Events: guide/howto/serve_sse/index.md
    - Serve Websockets: guide/howto/serve_websockets/index.md
    - Structure your logs with Events: guide/howto/structure_your_logs_with_events/index.md
    - Test using Service Virtualisation: guide/howto/test_using_service_virtualisation/index.md
    - Typesafe your API with lenses: guide/howto/typesafe_your_api_with_lenses/index.md
    - Secure and auth HTTP services: guide/howto/secure_and_auth_http/index.md
    - Use a custom OAuth Provider: guide/howto/use_a_custom_oauth_provider/index.md
    - Use a templating engines: guide/howto/use_a_templating_engine/index.md
    - Use HTML forms: guide/howto/use_html_forms/index.md
    - Use Multipart forms: guide/howto/use_multipart_forms/index.md
    - Create a Distributed Tracing tree: guide/howto/create_a_distributed_tracing_tree/index.md
  - Reference:
    - Overview: guide/reference/index.md
    - API docs: api/
    - Core: guide/reference/core/index.md
    - Server backend: guide/reference/servers/index.md
    - Serverless backend: guide/reference/serverless/index.md
    - HTTP & Websocket clients: guide/reference/clients/index.md
    - Typesafe contracts (OpenAPI3): guide/reference/contracts/index.md
    - JSON handling: guide/reference/json/index.md
    - Templating: guide/reference/templating/index.md
    - Multipart forms: guide/reference/multipart/index.md
    - Cloud Native Configuration: guide/reference/cloud_native/index.md
    - Cloud Events: guide/reference/cloud_events/index.md
    - Micrometer: guide/reference/micrometer/index.md
    - OpenTelemetry: guide/reference/opentelemetry/index.md
    - Resilience4J: guide/reference/resilience4j/index.md
    - AWS: guide/reference/aws/index.md
    - OAuth: guide/reference/oauth/index.md
    - GraphQL: guide/reference/graphql/index.md
    - JSON RPC: guide/reference/jsonrpc/index.md
    - XML handling: guide/reference/xml/index.md
    - YAML handling: guide/reference/yaml/index.md
    - Testing:
      - Overview: guide/reference/testing/index.md
      - Approval Testing: guide/reference/approvaltests/index.md
      - Chaos Testing: guide/reference/chaos/index.md
      - Hamkrest: guide/reference/hamkrest/index.md
      - Kotest: guide/reference/kotest/index.md
      - Service Virtualisation: guide/reference/servicevirtualisation/index.md
      - Strikt: guide/reference/strikt/index.md
      - WebDriver: guide/reference/webdriver/index.md
  - Blog:
    - Overview: blog/index.md
    - Meet http4k: blog/meet_http4k/index.md
    - Typesafe Websockets: blog/typesafe_websockets/index.md
    - Typesafe 12-factor config: blog/typesafe_configuration/index.md
    - Documenting http4k apps with OpenApi3: blog/documenting_apis_with_openapi/index.md
    - Retrospective on v3: blog/retrospective_v3/index.md
    - Nanoservices: blog/nanoservices/index.md
    - "Toolbox: Guns for show, knives for a pro": blog/toolbox/index.md
    - http4k v4 - 17 platforms and counting...: blog/http4k_v4/index.md
    - JCenter Shutdown: blog/regarding_jcenter/index.md
  - Changelog: changelog/index.md
  - http4k in action: in_action/index.md
  - Performance: performance/index.md
  - FAQ: faq/index.md
  - Getting support: support/index.md
  - Contribute/support http4k: contributing/index.md
  - Code of Conduct: code-of-conduct/index.md
