site_name: http4k
site_url: https://http4k.org
site_description: http4k is an HTTP toolkit written in Kotlin that enables the serving and consuming of HTTP services in a functional and consistent way.
site_author: David Denton (@daviddenton), IvanSanchez (@s4nchez)
copyright: 'Copyright &copy; 2017 - David Denton (@daviddenton), IvanSanchez (@s4nchez)'
remote_branch: master
repo_url: https://github.com/http4k/http4k/
theme: 'material'
theme_dir: ./docs/theme
google_analytics: ['UA-69281315-11', 'http4k.org']
markdown_extensions:
  - meta
  - codehilite
extra_css:
  - ./css/site.css
extra:
  palette:
    primary: 'indigo'
    accent: 'blue'
  logo: img/logo_1100x200_white_on_blue_trans.png
edit_uri: edit/master/src/docs/
strict: true
pages:
  - Introduction: index.md
  - Rationale & Concepts: rationale/index.md
  - Installation:  installation/index.md
  - Getting started: quickstart/index.md
  - Developer Guide:
    - Modules:
      - AWS: guide/modules/aws/index.md
      - Core: guide/modules/core/index.md
      - Hamkrest: guide/modules/hamkrest/index.md
      - HTTP/Websocket client: guide/modules/clients/index.md
      - Message formats: guide/modules/message_formats/index.md
      - Multipart forms: guide/modules/multipart/index.md
      - Resilience: guide/modules/resilience/index.md
      - Server backend: guide/modules/servers/index.md
      - Serverless backend: guide/modules/serverless/index.md
      - Templating: guide/modules/templating/index.md
      - Typesafe contracts: guide/modules/contracts/index.md
      - WebDriver: guide/modules/webdriver/index.md
    - Application Testing: guide/testing/index.md
    - Worked TDD Example:
      - Introduction: guide/example/index.md
      - 1. Building a walking skeleton: guide/example/_1_building_a_walking_skeleton/index.md
      - 2. Adding an endpoint: guide/example/_2_adding_the_first_endpoint/index.md
      - 3. Adding another endpoint: guide/example/_3_adding_the_second_endpoint/index.md
      - 4. An external dependency: guide/example/_4_adding_an_external_dependency/index.md
  - Cookbook:
    - Server as a function: cookbook/server_as_a_function/index.md
    - Client as a function: cookbook/client_as_a_function/index.md
    - Container integration: cookbook/container_integration/index.md
    - Simple routing: cookbook/simple_routing/index.md
    - Nestable routes: cookbook/nestable_routes/index.md
    - JSON messaging: cookbook/using_json/index.md
    - Templating engines: cookbook/using_templates/index.md
    - Typesafe RequestContexts: cookbook/request_context/index.md
    - Typesafe HTTP requests with lenses: cookbook/typesafe_http_requests_with_lenses/index.md
    - HTML forms: cookbook/html_forms/index.md
    - Multipart forms: cookbook/multipart_forms/index.md
    - Generating data classes for messages: cookbook/generating_data_classes/index.md
    - Websockets: cookbook/websockets/index.md
    - Typesafe HTTP contracts: cookbook/typesafe_http_contracts/index.md
    - Monitoring http4k: cookbook/monitoring/index.md
    - Recording/replaying HTTP traffic: cookbook/record_and_replay/index.md
    - Test driven apps: cookbook/test_driven_apps/index.md
  - Performance: performance/index.md
  - In action: in_action/index.md
  - Blog:
    - Meet http4k: blog/meet_http4k/index.md
    - Typesafe Websockets: blog/typesafe_websockets/index.md
  - Changelog: changelog/index.md
  - Contribute/Support http4k: contributing/index.md
  - FAQ: faq/index.md
  - Help & Support: support/index.md
