site_name: http4k
site_url: https://www.http4k.org/
site_description: The Functional toolkit for Kotlin HTTP applications
site_author: David Denton (@daviddenton), Ivan Sanchez (@s4nchez)
copyright: 'Copyright &copy; 2021 - David Denton (@daviddenton), IvanSanchez (@s4nchez)'
remote_branch: master
repo_url: https://github.com/http4k/http4k/
theme:
  name: 'material'
  custom_dir: ./docs/theme
  static_templates:
      - ./index.html
  palette:
    primary: 'indigo'
    accent: 'blue'
  logo: img/logo_1100x200_white_on_blue_trans.png
google_analytics: ['UA-125143867-1', 'auto']
markdown_extensions:
  - meta
  - codehilite
  - toc:
      permalink: True
      separator: "_"
extra_css:
  - ./css/site.css
extra:
  logo: img/logo_1100x200_white_on_blue_trans.png
edit_uri: edit/master/src/docs/
strict: false
nav:
  - Introduction: documentation/index.md
  - Quickstart: quickstart/index.md
  - How these docs are organised: index.md
  - Explanation:
      - Rationale: explanation/rationale.md
      - HTTP: explanation/http.md
      - Serverless: explanation/serverless.md
      - WebSockets: explanation/websockets.md
      - Server-Sent Events: explanation/server-sent-events.md
  - Tutorials:
      - ABC: how-to/abc/index.md
      - XYZ: how-to/xyz/index.md
  - How-to guides:
      - How to use this guide: howto/index.md
      - Server as a function: howto/server_as_a_function/index.md
      - Client as a function: howto/client_as_a_function/index.md
      - Container integration: howto/container_integration/index.md
      - Simple routing: howto/simple_routing/index.md
      - Nestable routes: howto/nestable_routes/index.md
      - OpenAPI contracts/routing: howto/typesafe_http_contracts/index.md
      - Templating engines: howto/using_templates/index.md
      - Typesafe RequestContexts: howto/request_context/index.md
      - Typesafe HTTP requests with lenses: howto/typesafe_http_requests_with_lenses/index.md
      - Custom JSON marshallers: howto/custom_json_marshallers/index.md
      - HTML forms: howto/html_forms/index.md
      - Multipart forms: howto/multipart_forms/index.md
      - WebJars: howto/webjars/index.md
      - Websockets: howto/websockets/index.md
      - Server-Sent Events: howto/sse/index.md
      - Structured Logging with Events: howto/structured_logging_with_events/index.md
      - Basic OAuth Server configuration: howto/basic_oauth_authorization_server/index.md
      - Custom OAuth Provider configuration: howto/custom_oauth_provider/index.md
      - Custom Server (SSL): howto/customised_servers/index.md
      - Service Virtualisation with Servirtium: howto/service_virtualisation/index.md
      - Principal lookup: howto/principal_lookup/index.md
      - Monitoring http4k: howto/monitoring/index.md
      - Recording/replaying HTTP traffic: howto/record_and_replay/index.md
      - Test driven apps: howto/test_driven_apps/index.md
  - Reference:
    - Overview: reference/index.md
    - API docs: reference/api/index.md
    - Core: reference/core/index.md
    - Server backend: reference/servers/index.md
    - Serverless backend: reference/serverless/index.md
    - HTTP & Websocket clients: reference/clients/index.md
    - Typesafe contracts (OpenAPI3): reference/contracts/index.md
    - JSON handling: reference/json/index.md
    - Templating: reference/templating/index.md
    - Multipart forms: reference/multipart/index.md
    - Cloud Native Configuration: reference/cloud_native/index.md
    - Cloud Events: reference/cloud_events/index.md
    - Micrometer: reference/micrometer/index.md
    - OpenTelemetry: reference/opentelemetry/index.md
    - Resilience4J: reference/resilience4j/index.md
    - AWS: reference/aws/index.md
    - OAuth: reference/oauth/index.md
    - GraphQL: reference/graphql/index.md
    - JSON RPC: reference/jsonrpc/index.md
    - XML handling: reference/xml/index.md
    - YAML handling: reference/yaml/index.md
    - Testing:
      - Overview: reference/testing/index.md
      - Hamkrest: reference/hamkrest/index.md
      - Kotest: reference/kotest/index.md
      - WebDriver: reference/webdriver/index.md
      - Approval Testing: reference/approvaltests/index.md
      - Chaos Testing: reference/chaos/index.md
      - Service Virtualisaion: reference/servicevirtualisation/index.md
  - Blog:
      - Overview: blog/index.md
      - Meet http4k: blog/meet_http4k/index.md
      - Typesafe Websockets: blog/typesafe_websockets/index.md
      - TDDing http4k: blog/tdding_http4k/index.md
      - Typesafe 12-factor config: blog/typesafe_configuration/index.md
      - Documenting http4k apps with OpenApi3: blog/documenting_apis_with_openapi/index.md
      - Retrospective on v3: blog/retrospective_v3/index.md
      - Nanoservices: blog/nanoservices/index.md
      - "Toolbox: Guns for show, knives for a pro": blog/toolbox/index.md
      - http4k v4 - 17 platforms and counting...: blog/http4k_v4/index.md
      - JCenter Shutdown: blog/regarding_jcenter/index.md
  - Changelog: changelog/index.md
  - http4k in action: in_action/index.md
  - Performance: performance/index.md
  - FAQ: faq/index.md
  - Getting support: support/index.md
  - Contribute/support http4k: contributing/index.md
  - Code of Conduct: code-of-conduct/index.md
  - API docs: api/index.md
