site_name: http4k
site_url: https://www.http4k.org/
site_description: http4k is an HTTP toolkit written in Kotlin that enables the serving and consuming of HTTP services in a functional and consistent way.
site_author: David Denton (@daviddenton), IvanSanchez (@s4nchez)
copyright: 'Copyright &copy; 2020 - David Denton (@daviddenton), IvanSanchez (@s4nchez)'
remote_branch: master
repo_url: https://github.com/http4k/http4k/
theme:
  name: 'material'
  custom_dir: ./docs/theme
  palette:
    primary: 'indigo'
    accent: 'blue'
  logo: img/logo_1100x200_white_on_blue_trans.png
google_analytics: ['UA-125143867-1', 'auto']
markdown_extensions:
  - meta
  - codehilite
extra_css:
  - ./css/site.css
extra:
  logo: img/logo_1100x200_white_on_blue_trans.png
edit_uri: edit/master/src/docs/
strict: true
nav:
  - Introduction: index.md
  - Rationale & Concepts: rationale/index.md
  - Installation:  installation/index.md
  - Getting started: quickstart/index.md
  - Developer Guide:
    - Modules:
      - Overview: guide/modules/index.md
      - AWS: guide/modules/aws/index.md
      - Core: guide/modules/core/index.md
      - JSON handling: guide/modules/json/index.md
      - HTTP & Websocket clients: guide/modules/clients/index.md
      - Metrics: guide/modules/metrics/index.md
      - Multipart forms: guide/modules/multipart/index.md
      - Resilience: guide/modules/resilience/index.md
      - Server backend: guide/modules/servers/index.md
      - Serverless backend: guide/modules/serverless/index.md
      - Templating: guide/modules/templating/index.md
      - Typesafe contracts (OpenAPI3): guide/modules/contracts/index.md
      - OAuth: guide/modules/oauth/index.md
      - Cloud native Configuration: guide/modules/cloud_native/index.md
      - JSON RPC: guide/modules/jsonrpc/index.md
      - XML handling: guide/modules/xml/index.md
      - YAML handling: guide/modules/yaml/index.md
      - Hamkrest: guide/modules/hamkrest/index.md
      - Approval Testing: guide/modules/approvaltests/index.md
      - WebDriver: guide/modules/webdriver/index.md
      - Chaos Testing: guide/modules/chaos/index.md
      - Service Virtualisaion: guide/modules/servicevirtualisation/index.md
    - Application Testing: guide/testing/index.md
  - Tutorials:
    - TDDing http4k: tutorials/tdding_http4k/index.md
    - Documenting http4k apps with OpenApi3: tutorials/documenting_apis_with_openapi/index.md
  - Cookbook:
    - How to use this guide: cookbook/index.md
    - Server as a function: cookbook/server_as_a_function/index.md
    - Client as a function: cookbook/client_as_a_function/index.md
    - Container integration: cookbook/container_integration/index.md
    - Simple routing: cookbook/simple_routing/index.md
    - Service Virtualisation with Servirtium: cookbook/service_virtualisation/index.md
    - Nestable routes: cookbook/nestable_routes/index.md
    - Templating engines: cookbook/using_templates/index.md
    - Typesafe RequestContexts: cookbook/request_context/index.md
    - Typesafe HTTP requests with lenses: cookbook/typesafe_http_requests_with_lenses/index.md
    - Custom JSON marshallers: cookbook/custom_json_marshallers/index.md
    - HTML forms: cookbook/html_forms/index.md
    - Multipart forms: cookbook/multipart_forms/index.md
    - Generating data classes for messages: cookbook/generating_data_classes/index.md
    - Websockets: cookbook/websockets/index.md
    - Typesafe HTTP contracts: cookbook/typesafe_http_contracts/index.md
    - Structured Logging with Events: cookbook/structured_logging_with_events/index.md
    - Basic OAuth Server configuration: cookbook/basic_oauth_authorization_server/index.md
    - Custom OAuth Provider configuration: cookbook/custom_oauth_provider/index.md
    - Custom Server (SSL): cookbook/customised_servers/index.md
    - Principal lookup: cookbook/principal_lookup/index.md
    - Monitoring http4k: cookbook/monitoring/index.md
    - Recording/replaying HTTP traffic: cookbook/record_and_replay/index.md
    - Test driven apps: cookbook/test_driven_apps/index.md
    - Nanoservices: cookbook/nanoservices/index.md
  - Performance: performance/index.md
  - In action: in_action/index.md
  - Blog:
    - Meet http4k: blog/meet_http4k/index.md
    - Typesafe Websockets: blog/typesafe_websockets/index.md
  - Getting Support: support/index.md
  - Contribute/Support http4k: contributing/index.md
  - API docs: api/index.md
  - Changelog: changelog/index.md
  - FAQ: faq/index.md
