site_name: http4k
site_url: https://www.http4k.org/
site_description: The Functional toolkit for Kotlin HTTP applications
site_author: David Denton (@daviddenton), Ivan Sanchez (@s4nchez)
copyright: 'Copyright &copy; 2021 - David Denton (@daviddenton), IvanSanchez (@s4nchez)'
remote_branch: master
repo_url: https://github.com/http4k/http4k/
theme:
  name: 'material'
  custom_dir: ./docs/theme
  static_templates:
      - ./index.html
  palette:
    primary: 'indigo'
    accent: 'blue'
  logo: img/logo_1100x200_white_on_blue_trans.png
google_analytics: ['UA-125143867-1', 'auto']
markdown_extensions:
  - meta
  - codehilite
  - toc:
      permalink: True
      separator: "_"
extra_css:
  - ./css/site.css
extra:
  logo: img/logo_1100x200_white_on_blue_trans.png
edit_uri: edit/master/src/docs/
strict: false
nav:
  - Introduction: documentation/index.md
  - About the docs: index.md
  - Concepts:
    - Rationale: concepts/rationale.md
    - HTTP: concepts/http.md
    - Serverless: concepts/serverless.md
    - Lens: concepts/lens.md
    - WebSockets: concepts/websockets.md
    - Server-Sent Events: concepts/server-sent-events.md
  - Tutorials:
    - Quickstart: tutorials/quickstart/index.md
    - TDDing http4k: tutorials/tdding_http4k/index.md
  - How-to guides:
    - Server as a function: guide/howto/server_as_a_function/index.md
    - Client as a function: guide/howto/client_as_a_function/index.md
    - Container integration: guide/howto/container_integration/index.md
    - Simple routing: guide/howto/simple_routing/index.md
    - Nestable routes: guide/howto/nestable_routes/index.md
    - OpenAPI contracts/routing: guide/howto/typesafe_http_contracts/index.md
    - Templating engines: guide/howto/using_templates/index.md
    - Typesafe RequestContexts: guide/howto/request_context/index.md
    - Typesafe HTTP requests with lenses: guide/howto/typesafe_http_requests_with_lenses/index.md
    - Custom JSON marshallers: guide/howto/custom_json_marshallers/index.md
    - GraphQL: guide/howto/graphql/index.md
    - HTML forms: guide/howto/html_forms/index.md
    - Multipart forms: guide/howto/multipart_forms/index.md
    - WebJars: guide/howto/webjars/index.md
    - Websockets: guide/howto/websockets/index.md
    - Server-Sent Events: guide/howto/sse/index.md
    - Structured Logging with Events: guide/howto/structured_logging_with_events/index.md
    - Basic OAuth Server configuration: guide/howto/basic_oauth_authorization_server/index.md
    - Custom OAuth Provider configuration: guide/howto/custom_oauth_provider/index.md
    - Custom Server (SSL): guide/howto/customised_servers/index.md
    - Service Virtualisation with Servirtium: guide/howto/service_virtualisation/index.md
    - Principal lookup: guide/howto/principal_lookup/index.md
    - Monitoring http4k: guide/howto/monitoring/index.md
    - Recording/replaying HTTP traffic: guide/howto/record_and_replay/index.md
    - Test driven apps: guide/howto/test_driven_apps/index.md
  - Module reference:
    - Overview: guide/reference/index.md
    - API docs: guide/reference/api/index.md
    - Core: guide/reference/core/index.md
    - Server backend: guide/reference/servers/index.md
    - Serverless backend: guide/reference/serverless/index.md
    - HTTP & Websocket clients: guide/reference/clients/index.md
    - Typesafe contracts (OpenAPI3): guide/reference/contracts/index.md
    - JSON handling: guide/reference/json/index.md
    - Templating: guide/reference/templating/index.md
    - Multipart forms: guide/reference/multipart/index.md
    - Cloud Native Configuration: guide/reference/cloud_native/index.md
    - Cloud Events: guide/reference/cloud_events/index.md
    - Micrometer: guide/reference/micrometer/index.md
    - OpenTelemetry: guide/reference/opentelemetry/index.md
    - Resilience4J: guide/reference/resilience4j/index.md
    - AWS: guide/reference/aws/index.md
    - OAuth: guide/reference/oauth/index.md
    - GraphQL: guide/reference/graphql/index.md
    - JSON RPC: guide/reference/jsonrpc/index.md
    - XML handling: guide/reference/xml/index.md
    - YAML handling: guide/reference/yaml/index.md
    - Testing:
      - Overview: guide/reference/testing/index.md
      - Hamkrest: guide/reference/hamkrest/index.md
      - Kotest: guide/reference/kotest/index.md
      - WebDriver: guide/reference/webdriver/index.md
      - Approval Testing: guide/reference/approvaltests/index.md
      - Chaos Testing: guide/reference/chaos/index.md
      - Service Virtualisaion: guide/reference/servicevirtualisation/index.md
  - Blog:
    - Overview: blog/index.md
    - Meet http4k: blog/meet_http4k/index.md
    - Typesafe Websockets: blog/typesafe_websockets/index.md
    - Typesafe 12-factor config: blog/typesafe_configuration/index.md
    - Documenting http4k apps with OpenApi3: blog/documenting_apis_with_openapi/index.md
    - Retrospective on v3: blog/retrospective_v3/index.md
    - Nanoservices: blog/nanoservices/index.md
    - "Toolbox: Guns for show, knives for a pro": blog/toolbox/index.md
    - http4k v4 - 17 platforms and counting...: blog/http4k_v4/index.md
    - JCenter Shutdown: blog/regarding_jcenter/index.md
  - Changelog: changelog/index.md
  - http4k in action: in_action/index.md
  - Performance: performance/index.md
  - FAQ: faq/index.md
  - Getting support: support/index.md
  - Contribute/support http4k: contributing/index.md
  - Code of Conduct: code-of-conduct/index.md
