on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  check-new-version:
    runs-on: ubuntu-latest
    outputs:
      requires-broadcast: ${{ steps.check-version.outputs.requires-broadcast }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Check new version
        id: check-version
        run: ./release-broadcast-checker.sh
        shell: bash
  broadcast-release:
    runs-on: ubuntu-latest
    needs: [check-new-version]
    if: jobs.check-new-version.outputs.requires-broadcast == 'true'
    steps:
      - name: Broadcast
        run: echo "new version available!"
        shell: bash
