name: Broadcast Release
on:
  schedule:
    - cron: '0 * * * *' # every hour
  push:
    branches:
      - master
jobs:
  check-new-version:
    runs-on: ubuntu-latest
    outputs:
      requires-broadcast: ${{ steps.check-version.outputs.requires-broadcast }}
      version: ${{ steps.check-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Check new version
        id: check-version
        shell: bash
        run: |
          LOCAL_VERSION=$(jq -r .http4k.version ./version.json)
          S3_VERSION=$(aws s3 cp s3://http4k/latest-broadcasted-version.txt -)

          if [[ $S3_VERSION == $LOCAL_VERSION ]]; then
            echo "Version $LOCAL_VERSION has been broadcasted already."
            echo "requires-broadcast=false" >> $GITHUB_OUTPUT
            exit 0
          fi;

          echo "Latest broadcasted version was ${S3_VERSION}. Checking for ${LOCAL_VERSION} in maven central..."

          MC_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            "https://repo1.maven.org/maven2/org/http4k/http4k-core/${LOCAL_VERSION}/http4k-core-${LOCAL_VERSION}.pom"
          )

          if [[ $MC_STATUS == "200" ]]; then
            echo "Version $LOCAL_VERSION available in MC. Preparing for broadcast..."
            echo "${LOCAL_VERSION}" | aws s3 cp - s3://http4k/latest-broadcasted-version.txt
            echo "requires-broadcast=true" >> $GITHUB_OUTPUT
            echo "version=${LOCAL_VERSION}" >> $GITHUB_OUTPUT
          fi;
  broadcast-release:
    runs-on: ubuntu-latest
    needs: [check-new-version]
    if: ${{ needs.check-new-version.outputs.requires-broadcast == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Grab tag name
        uses: olegtarasov/get-tag@v2.1.2
        id: tagName
      - name: Dispatch Release Event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ORG_PUBLIC_REPO_WORKFLOW_TRIGGERING }}
          repository: http4k/http4k
          event-type: http4k-release
          client-payload: '{"version": "${{ needs.check-new-version.outputs.version }}"}'
