on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  create-toolbox-release:
    runs-on: ubuntu-latest
    steps:
      - name: Grab tag name
        uses: olegtarasov/get-tag@v2
        id: tagName
      - name: Trigger toolbox
        uses: peter-evans/repository-dispatch@v1.1.1
        with:
          token: ${{ secrets.TOOLBOX_REPO_TOKEN }}
          repository: http4k/toolbox
          event-type: http4k-release
          client-payload: '{"version": "${{ steps.tagName.outputs.tag }}"}'
