on: [repository_dispatch]
jobs:
  create-toolbox-release:
    if: github.event.action == 'http4k-release'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger toolbox
        uses: peter-evans/repository-dispatch@v1.1.1
        with:
          token: ${{ secrets.TOOLBOX_REPO_TOKEN }}
          repository: http4k/toolbox
          event-type: http4k-release
          client-payload: '{"version": "${{ github.event.client_payload.version }}"}'
