name: New Release - Slack
on:
  repository_dispatch:
    types:
    - http4k-release
permissions:
  contents: read
jobs:
  slackify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: Notify Slack
      run: bin/notify_slack.sh ${{ github.event.client_payload.version }}
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      shell: bash