on:
  push:
    tags:
      - '*'
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  release-to-bintray:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./release-ci.sh
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}
      - name: Grab tag name
        uses: olegtarasov/get-tag@v2
        id: tagName
      - uses: peter-evans/repository-dispatch@v1.1.1
        with:
          repository: http4k/http4k
          event-type: http4k-release
          client-payload: '{"version": "${{ steps.tagName.outputs.tag }}"}'
