on: [repository_dispatch]
jobs:
  slackify:
    if: github.event.action == 'http4k-release2'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./notify-slack.sh
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
